### ISSUE TITLE
Instead of decreasing opacity you could set compositeOperation: 'lighter'

### ISSUE THREAD

**Issue by feuerste** [imoutsatsos/osdUseCaseHCS#2]
In https://github.com/imoutsatsos/osdUseCaseHCS/blob/66489c54504f9c2f8bf692e0d0cfc972f925aeee/js/imageGalleryAnnoDemo.js#L53 you could set the opacity to 1 and initialize the Openseadragon viewer with `compositeOperation: 'lighter'`. This would solve the brightness problems.
Hope this helps!

**Comment by imoutsatsos** [comment]
@feuerste Thanks for the suggestion. Works great now! I have updated the composite images in the readme with the improved color composites.
